package com.pms.rcm.sys.vo;


import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
 
 

/**
 * Dept generated by MyEclipse - Hibernate Tools
 */
@Entity
@Table(name="Department_info")
public class Dept  implements java.io.Serializable,Comparable<Dept>{

	

    // Fields    
	 @Id
	 @GeneratedValue(generator="system-uuid")
	 @GenericGenerator(name = "system-uuid",strategy="uuid")
	 @Column(name="id")
     private String id;
	 @Column(name="cas_code")
     private String casCode;
	 @Column(name="Department_No")
     private String deptNo; 
	 @Column(name="Department_name")
     private String deptName; 
	 @Column(name="Department_description")
     private String text;
	 @Column(name="parent_id")
     private String parentId; 
	 @Column(name="Department_Type")
     private String deptType;
	 @Transient  
     private List<Role> roleList = new ArrayList<Role>();//不持久化
	 @Transient  
     private List<User> userList = new ArrayList<User>();//不持久化 
	 @Transient  
	 private String target; 
	 @Transient  
	 private String treeurl;
	 @Transient  
	 private List<Dept> subDepartment;
	 @Transient  
	 private boolean hasDepartment = false;
	  
	 @Column(name="Department_contacts")
	 private String deptContacts; 
	 @Column(name="Department_contacts_tel")
	  String deptContactsTel; 
	 @Column(name="Department_addr")
	 private String deptAddr;
	 @Column(name="Department_other")
	 private String deptOther;
	 
	 
     public String getDeptContacts() {
		return deptContacts;
	}

	public void setDeptContacts(String deptContacts) {
		this.deptContacts = deptContacts;
	}

	public String getDeptContactsTel() {
		return deptContactsTel;
	}

	public void setDeptContactsTel(String deptContactsTel) {
		this.deptContactsTel = deptContactsTel;
	}

	public String getDeptAddr() {
		return deptAddr;
	}

	public void setDeptAddr(String deptAddr) {
		this.deptAddr = deptAddr;
	}

	public String getDeptOther() {
		return deptOther;
	}

	public void setDeptOther(String deptOther) {
		this.deptOther = deptOther;
	}

	public List<Dept> getSubDepartment() {
		return subDepartment;
	}

	public void setSubDepartment(List<Dept> subDepartment) {
		this.subDepartment = subDepartment;
	}

	public boolean isHasDepartment() {
		return hasDepartment;
	}

	public void setHasDepartment(boolean hasDepartment) {
		this.hasDepartment = hasDepartment;
	}

	public String getTarget() {
		return target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getTreeurl() {
		return treeurl;
	}

	public void setTreeurl(String treeurl) {
		this.treeurl = treeurl;
	}

	 
	/** default constructor */
    public Dept() {
    }
 
   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getCasCode() {
        return this.casCode;
    }
    
    public void setCasCode(String casCode) {
        this.casCode = casCode;
    }

    public String getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    
    

	public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

        
	
	public List<Role> getRoleList() {
		return roleList;
	}

	public void setRoleList(List<Role> roleList) {
		this.roleList = roleList;
	}

	public void addRole(Role role){
	    this.roleList.add(role);
	}
	
	public List<User> getUserList() {
		return userList;
	}

	public void setUserList(List<User> userList) {
		this.userList = userList;
	}
	
	public void addUser(User user){
	    this.userList.add(user);
	}
	

    	
	/**
     * 
     * <li>方法名：getParentCasCode
     * <li>@return
     * <li>返回类型：String
     * <li>说明：获得父机构级联编号
     * <li>创建人：曾明辉
     * <li>创建日期：2008-11-21
     * <li>修改人： 
     * <li>修改日期：
     */
    public String getParentCasCode(){
    	if(casCode == null || casCode.length()<=3){
    		return "";
    	}
    	return casCode.substring(0,casCode.length()-3);
    }
    
    /**
     * 
     * <li>方法名：compareTo
     * <li>@param other
     * <li>@return
     * <li>返回类型：int
     * <li>说明：用于TreeSet排序
     * <li>创建人：曾明辉
     * <li>创建日期：2008-11-5
     * <li>修改人： 
     * <li>修改日期：2010-07-26
     */
    public int compareTo(Dept other) {
    	if (other == null || other.casCode == null || this.casCode == null){
			return 1;
		}
    	if(this.casCode.length() != other.casCode.length()){
    		Integer myLength = this.casCode.length();
    		return myLength.compareTo(other.casCode.length());
    	}
//    	if(! this.deptType.equals(other.deptType)){
//    		return this.deptType.compareTo(other.deptType);
//    	}
		return this.deptNo.compareTo(other.deptNo);//按系统编码的编号排序
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getDeptType() {
		return deptType;
	}

	public void setDeptType(String deptType) {
		this.deptType = deptType;
	}
 

    
    
    


    
}