package com.pms.rcm.sys.vo;


import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;



/**
 * Role generated by MyEclipse - Hibernate Tools
 */
@Entity
@Table(name="Role_info")
public class Role  implements java.io.Serializable,Comparable<Role> {

    // Fields    
	  // Fields    
	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name = "system-uuid",strategy="uuid")
	@Column(name="id")
     private String id; 
	@Column(name="role_Code")
     private String roleCode;
	@Column(name="role_Name")
     private String roleName; 
	@Column(name="remark")
     private String remark; 
	 @Transient  
	 private String parentId;
	 @Transient  
	 private List<Role> subRole;
	 @Transient  
	 private String target; 
	 @Transient  
	 private String treeurl;
	 
	 
    // Constructors

    

	public String getTarget() {
		return target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	public String getTreeurl() {
		return treeurl;
	}

	public void setTreeurl(String treeurl) {
		this.treeurl = treeurl;
	}

	public String getParentId() {
		return parentId;
	}

	public List<Role> getSubRole() {
		return subRole;
	}

	public void setSubRole(List<Role> subRole) {
		this.subRole = subRole;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/** default constructor */
    public Role() {
    }

	/** minimal constructor */
    public Role(String roleName) {
        this.roleName = roleName;
    }
    
   
   
    // Property accessors
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
 
    
    public String getRoleCode() {
		return roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
 

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
	@ManyToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
    @JoinTable(name = "Role_fucntion_distribute",joinColumns = {@JoinColumn(name = "ROLE_ID")},inverseJoinColumns = {@JoinColumn(name = "Function_page_id")})
    private Set<Menu> menuSet = new TreeSet<Menu>();//角色菜单集合
    /*@ManyToMany(cascade={CascadeType.PERSIST,CascadeType.REMOVE}, targetEntity=ModuleFun.class) */  
   /* @ManyToMany
	@JoinTable(name = "SYS_Role_Fun", joinColumns = @JoinColumn(name = "ROLE_ID"), inverseJoinColumns = @JoinColumn(name = "FUN_ID"))    
    private Set<ModuleFun> moduleFunSet = new TreeSet<ModuleFun>();//角色功能集合     
*/
    @ManyToMany(cascade = CascadeType.PERSIST, fetch = FetchType.EAGER)
	@JoinTable(name = "Role_Button", joinColumns = @JoinColumn(name = "ROLE_ID"), inverseJoinColumns = @JoinColumn(name = "BTN_ID"))    
	private Set<SysButton> sysOperationSet = new TreeSet<SysButton>();//角色功能集合    

	public Set<SysButton> getSysOperationSet() {
		return sysOperationSet;
	}

	public void setSysOperationSet(Set<SysButton> sysOperationSet) {
		this.sysOperationSet = sysOperationSet;
	}

	public Set<Menu> getMenuSet() {
		return menuSet;
	}

	public void setMenuSet(Set<Menu> menuSet) {
		this.menuSet = menuSet;
	}

	/*public Set<ModuleFun> getModuleFunSet() {
		return moduleFunSet;
	}

	public void setModuleFunSet(Set<ModuleFun> moduleFunSet) {
		this.moduleFunSet = moduleFunSet;
	}*/
	

	/**
	 * 
	 * <li>方法名：getMenuIds
	 * <li>@return
	 * <li>返回类型：String
	 * <li>说明：只获得菜单Id，用逗号间隔
	 * <li>创建人：曾明辉
	 * <li>创建日期：2008-11-27
	 * <li>修改人： 
	 * <li>修改日期：
	 */
	public String getMenuIds(){
		String ids = "";
		
		for (Menu menu : menuSet) {
			ids += menu.getId() + ",";
		}
		if(ids.lastIndexOf(",") > 0){
			ids = ids.substring(0,ids.lastIndexOf(","));
		}
		return ids;
	}
	/**
	 * 
	 * <li>方法名：getModuleFunIds
	 * <li>@return
	 * <li>返回类型：String
	 * <li>说明：只获得功能Id，用逗号间隔
	 * <li>创建人：曾明辉
	 * <li>创建日期：2008-11-27
	 * <li>修改人： 
	 * <li>修改日期：
	 */
	public String getModuleFunIds(){
		String ids = "";
		
		for (SysButton fun : sysOperationSet) {
			ids += fun.getId() + ",";
		}
		if(ids.lastIndexOf(",") > 0){
			ids = ids.substring(0,ids.lastIndexOf(","));
		}
		return ids;
	}
	
	/**
     * 
     * <li>方法名：compareTo
     * <li>@param other
     * <li>@return
     * <li>返回类型：int
     * <li>说明：用于TreeSet排序
     * <li>创建人：曾明辉
     * <li>创建日期：2008-11-7
     * <li>修改人： 
     * <li>修改日期：
     */
    public int compareTo(Role other) {
    	if (other == null || other.id == null || this.id == null){
			return 1;
		}
		return 0;
    	 
    }  




}